# Generated by Django 2.1 on 2019-03-17 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('occupation', models.CharField(max_length=20)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
